# Add from "owlapi"
cp -a owlapi/OWLRelation.java ../owlapi0/api/src/main/java/org/semanticweb/owlapi/model
cp -a owlapi/OWLRelation.java ../owlapi1/api/src/main/java/org/semanticweb/owlapi/model
cp -a owlapi/OWLRelationChangeListener.java ../owlapi0/api/src/main/java/org/semanticweb/owlapi/model
cp -a owlapi/OWLRelationChangeListener.java ../owlapi1/api/src/main/java/org/semanticweb/owlapi/model
cp -a owlapi/OWLRelationInstance.java ../owlapi0/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/OWLRelationInstance.java ../owlapi1/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/OWLRelationInstanceContainer.java ../owlapi0/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/OWLRelationInstanceContainer.java ../owlapi1/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
# Modify from "owlapi"
cp -a owlapi/OWLOntology.java ../owlapi0/api/src/main/java/org/semanticweb/owlapi/model
cp -a owlapi/OWLOntology.java ../owlapi1/api/src/main/java/org/semanticweb/owlapi/model
cp -a owlapi/OWLOntologyImpl.java ../owlapi0/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/OWLOntologyImpl.java ../owlapi1/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/Internals.java ../owlapi0/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/Internals.java ../owlapi1/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/InternalsImpl.java ../owlapi0/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/InternalsImpl.java ../owlapi1/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/AbstractInternalsImpl.java ../owlapi0/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/AbstractInternalsImpl.java ../owlapi1/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi
cp -a owlapi/RDFConstants.java ../owlapi0/parsers/src/main/java/org/semanticweb/owlapi/rdf/util
cp -a owlapi/RDFConstants.java ../owlapi1/parsers/src/main/java/org/semanticweb/owlapi/rdf/util
cp -a owlapi/RDFParser.java ../owlapi0/parsers/src/main/java/org/semanticweb/owlapi/rdf/syntax
cp -a owlapi/RDFParser.java ../owlapi1/parsers/src/main/java/org/semanticweb/owlapi/rdf/syntax
cp -a owlapi/OWLRDFConsumer.java ../owlapi0/parsers/src/main/java/org/coode/owlapi/rdfxml/parser
cp -a owlapi/OWLRDFConsumer.java ../owlapi1/parsers/src/main/java/org/coode/owlapi/rdfxml/parser
cp -a owlapi/RDFRendererBase.java ../owlapi0/parsers/src/main/java/org/coode/owlapi/rdf/renderer
cp -a owlapi/RDFRendererBase.java ../owlapi1/parsers/src/main/java/org/coode/owlapi/rdf/renderer
cp -a owlapi/OWLOntologyXMLNamespaceManager.java ../owlapi0/parsers/src/main/java/org/coode/xml
cp -a owlapi/OWLOntologyXMLNamespaceManager.java ../owlapi1/parsers/src/main/java/org/coode/xml
cp -a owlapi/RDFXMLRenderer.java ../owlapi0/parsers/src/main/java/org/coode/owlapi/rdf/rdfxml
cp -a owlapi/RDFXMLRenderer.java ../owlapi1/parsers/src/main/java/org/coode/owlapi/rdf/rdfxml
cp -a owlapi/XMLWriterImpl.java ../owlapi0/parsers/src/main/java/org/coode/xml
cp -a owlapi/XMLWriterImpl.java ../owlapi1/parsers/src/main/java/org/coode/xml
# Modify from "protege-owlapi"
cp -a protege-owlapi/WriteSafeOWLOntologyImpl.java ../protege-owlapi/src/main/java/org/protege/owlapi/concurrent
REM Modify from "owlviz"
cp -a owlviz/AbstractOWLClassGraphModel.java ../owlviz/src/main/java/uk/ac/man/cs/mig/coode/owlviz/model
# Add from "protege"
cp -a protege/selected-entity-view-relation-panel.xml ../protege/org.protege.editor.owl/src/main/resources
cp -a protege/OWLRelationViewComponent.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/view/relation
cp -a protege/OWLRelationList.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/view/relation
cp -a protege/OWLRelationCharacteristicsViewComponent.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/view/relation
cp -a protege/newRelationCreationPanel.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/view/relation
cp -a protege/OWLRelatedViewComponent.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/view/relation
cp -a protege/newRelatedCreationPanel.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/view/relation
cp -a protege/OWLRelationSelectionListener.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/model/selection
# Modify from "protege"
cp -a protege/plugin.xml ../protege/org.protege.editor.owl/src/main/resources
cp -a protege/viewconfig-classestab.xml ../protege/org.protege.editor.owl/src/main/resources
cp -a protege/viewconfig-entitiestab.xml ../protege/org.protege.editor.owl/src/main/resources
cp -a protege/SelectedEntityCardView.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/view
cp -a protege/OWLCellRendererSimple.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/renderer
cp -a protege/OWLSelectionModel.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/model/selection
cp -a protege/OWLSelectionModelImpl.java ../protege/org.protege.editor.owl/src/main/java/org/protege/editor/owl/model/selection