REM Add from "owlapi"
copy /Y owlapi\OWLRelation.java ..\owlapi0\api\src\main\java\org\semanticweb\owlapi\model
copy /Y owlapi\OWLRelation.java ..\owlapi1\api\src\main\java\org\semanticweb\owlapi\model
copy /Y owlapi\OWLRelationChangeListener.java ..\owlapi0\api\src\main\java\org\semanticweb\owlapi\model
copy /Y owlapi\OWLRelationChangeListener.java ..\owlapi1\api\src\main\java\org\semanticweb\owlapi\model
copy /Y owlapi\OWLRelationInstance.java ..\owlapi0\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\OWLRelationInstance.java ..\owlapi1\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\OWLRelationInstanceContainer.java ..\owlapi0\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\OWLRelationInstanceContainer.java ..\owlapi1\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
REM Modify from "owlapi"
copy /Y owlapi\OWLOntology.java ..\owlapi0\api\src\main\java\org\semanticweb\owlapi\model
copy /Y owlapi\OWLOntology.java ..\owlapi1\api\src\main\java\org\semanticweb\owlapi\model
copy /Y owlapi\OWLOntologyImpl.java ..\owlapi0\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\OWLOntologyImpl.java ..\owlapi1\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\Internals.java ..\owlapi0\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\Internals.java ..\owlapi1\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\InternalsImpl.java ..\owlapi0\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\InternalsImpl.java ..\owlapi1\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\AbstractInternalsImpl.java ..\owlapi0\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\AbstractInternalsImpl.java ..\owlapi1\impl\src\main\java\uk\ac\manchester\cs\owl\owlapi
copy /Y owlapi\RDFConstants.java ..\owlapi0\parsers\src\main\java\org\semanticweb\owlapi\rdf\util
copy /Y owlapi\RDFConstants.java ..\owlapi1\parsers\src\main\java\org\semanticweb\owlapi\rdf\util
copy /Y owlapi\RDFParser.java ..\owlapi0\parsers\src\main\java\org\semanticweb\owlapi\rdf\syntax
copy /Y owlapi\RDFParser.java ..\owlapi1\parsers\src\main\java\org\semanticweb\owlapi\rdf\syntax
copy /Y owlapi\OWLRDFConsumer.java ..\owlapi0\parsers\src\main\java\org\coode\owlapi\rdfxml\parser
copy /Y owlapi\OWLRDFConsumer.java ..\owlapi1\parsers\src\main\java\org\coode\owlapi\rdfxml\parser
copy /Y owlapi\RDFRendererBase.java ..\owlapi0\parsers\src\main\java\org\coode\owlapi\rdf\renderer
copy /Y owlapi\RDFRendererBase.java ..\owlapi1\parsers\src\main\java\org\coode\owlapi\rdf\renderer
copy /Y owlapi\OWLOntologyXMLNamespaceManager.java ..\owlapi0\parsers\src\main\java\org\coode\xml
copy /Y owlapi\OWLOntologyXMLNamespaceManager.java ..\owlapi1\parsers\src\main\java\org\coode\xml
copy /Y owlapi\RDFXMLRenderer.java ..\owlapi0\parsers\src\main\java\org\coode\owlapi\rdf\rdfxml
copy /Y owlapi\RDFXMLRenderer.java ..\owlapi1\parsers\src\main\java\org\coode\owlapi\rdf\rdfxml
copy /Y owlapi\XMLWriterImpl.java ..\owlapi0\parsers\src\main\java\org\coode\xml
copy /Y owlapi\XMLWriterImpl.java ..\owlapi1\parsers\src\main\java\org\coode\xml
REM Modify from "protege-owlapi"
copy /Y protege-owlapi\WriteSafeOWLOntologyImpl.java ..\protege-owlapi\src\main\java\org\protege\owlapi\concurrent
REM Modify from "owlviz"
copy /Y owlviz\AbstractOWLClassGraphModel.java ..\owlviz\src\main\java\uk\ac\man\cs\mig\coode\owlviz\model
REM Add from "protege"
copy /Y protege\selected-entity-view-relation-panel.xml ..\protege\org.protege.editor.owl\src\main\resources
copy /Y protege\OWLRelationViewComponent.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\view\relation
copy /Y protege\OWLRelationList.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\view\relation
copy /Y protege\OWLRelationCharacteristicsViewComponent.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\view\relation
copy /Y protege\newRelationCreationPanel.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\view\relation
copy /Y protege\OWLRelatedViewComponent.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\view\relation
copy /Y protege\newRelatedCreationPanel.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\view\relation
copy /Y protege\OWLRelationSelectionListener.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\model\selection
REM Modify from "protege"
copy /Y protege\plugin.xml ..\protege\org.protege.editor.owl\src\main\resources
copy /Y protege\viewconfig-classestab.xml ..\protege\org.protege.editor.owl\src\main\resources
copy /Y protege\viewconfig-entitiestab.xml ..\protege\org.protege.editor.owl\src\main\resources
copy /Y protege\SelectedEntityCardView.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\view
copy /Y protege\OWLCellRendererSimple.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\ui\renderer
copy /Y protege\OWLSelectionModel.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\model\selection
copy /Y protege\OWLSelectionModelImpl.java ..\protege\org.protege.editor.owl\src\main\java\org\protege\editor\owl\model\selection