language: java

jdk:
  - oraclejdk7
  - openjdk7

notifications:
  email:
    recipients:
      - vendetti@stanford.edu
      - tudorache@stanford.edu
      - csnyulas@stanford.edu
      - horridge@stanford.edu
    on_success: never
    on_failure: always


